---
title: "実践編"
subtitle: "4章 デザイン行列を用いた一般線形回帰モデル"
author: "宇畑 優太（1260404）"
date: today
execute: 
  echo: true
  warning: false
  message: true
format: 
  pdf:
    fig-width: 5
    fig-height: 3
    number-sections: true
    include-in-header:
      - text: \setlength{\parindent}{1em}
pdf-engine: lualatex
documentclass: ltjsarticle 
lang: ja
---

# 準備

```{r global_option}
#| include: false
#| message: false

## PDF に出力する際は cairo を使用する
if (knitr::is_latex_output()) {
  knitr::opts_chunk$set(dev = "cairo_pdf")
}

#パッケージの読み込み
pacman::p_load(tidyverse, 
               broom, 
               coefplot, 
               texreg,
               bayesplot,
               rstan,
               rstanrm,
               parallel,
               posterior,
               cmdstanr,
               patchwork,
               brms)

#日本語の設定
if (.Platform$OS.type == "windows") { 
  if (require(fontregisterer)) {
    my_font <- "Yu Gothic"
  } else {
    my_font <- "Japan1"
  }
} else if (capabilities("aqua")) {
  my_font <- "HiraginoSans-W3"
} else {
  my_font <- "IPAexGothic"
}

theme_set(theme_gray(base_size = 9,
                     base_family = my_font))

#計算の高速化
rstan_options(auto_write = TRUE) 
options(mc.cores = parallel::detectCores())
```







# formula構文を用いたデザイン行列の作成


```{r}
beer_data <- read.csv("data/3-2-1-beer-sales-2.csv")
```


デザイン行列はformulaと呼ばれる特殊記号を用いて作成する
```{r}
#デザイン行列の作成
formula_lm <- formula(sales ~ temperature)
X <- model.matrix(formula_lm, beer_data)
head(X, n = 5)
```

# デザイン行列を使うためのStanファイルの修正

色々やった

# MCMCの実行

デザイン行列をlistにまとめてから，MCMCを実行する.

```{r}
#| results: hide
N <- nrow(beer_data)
K <- 2
Y <- beer_data$sales
data_list_design <- list(N = N, K = K, Y = Y, X = X)

mcmc_result_design <- stan(
  file = "stan/3_4_1_design_matrix.stan",
  data = data_list_design,
  seed = 1
)
```

```{r}
print(mcmc_result_design, 
      probs = c(0.025, 0.5, 0.975))
```



# test


